FROM rocksdb-builder

WORKDIR /example
COPY ./example/* .

# WORKDIR /example/build
# cmake -DRocksdb_DIR="/tmp/rocksdb/lib/cmake/rocksdb" -DCMAKE_BUIlD_TYPE=Release ..
# cmake --build .

ENV LD_LIBRARY_PATH=/tmp/rocksdb/lib
RUN g++ -o ./rocksdb_example example.cpp -L/tmp/rocksdb/lib -lrocksdb -I/tmp/rocksdb/include

ENTRYPOINT ["./rocksdb_example"]
